version: '3'
services:
  pulsar_manager:
    image: apachepulsar/pulsar-manager:v0.3.0
    ports:
    - 9527:9527
    - 7750:7750
    environment:
    - SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties
